@file:JvmName("GeneralConstants")

package me.lizardofoz.inventorio.util

const val DEEP_POCKETS_MAX_LEVEL = 3
const val VANILLA_ROW_LENGTH = 9

const val MAIN_INVENTORY_SIZE = VANILLA_ROW_LENGTH * 4
const val DEEP_POCKETS_MAX_SIZE = DEEP_POCKETS_MAX_LEVEL * VANILLA_ROW_LENGTH
const val ARMOR_SIZE = 4
const val TOOL_BELT_SIZE = 5
const val UTILITY_BELT_SIZE = 8

@JvmField val HANDLER_ADDON_CRAFTING_GRID_RANGE = 0 until 5
@JvmField val HANDLER_ADDON_ARMOR_RANGE = HANDLER_ADDON_CRAFTING_GRID_RANGE.last + 1 expandBy ARMOR_SIZE
@JvmField val HANDLER_ADDON_MAIN_INVENTORY_RANGE = HANDLER_ADDON_ARMOR_RANGE.last + 1 expandBy MAIN_INVENTORY_SIZE
@JvmField val HANDLER_ADDON_DUD_OFFHAND_RANGE = HANDLER_ADDON_MAIN_INVENTORY_RANGE.last + 1

@JvmField val HANDLER_ADDON_MAIN_INVENTORY_WITHOUT_HOTBAR_RANGE = HANDLER_ADDON_MAIN_INVENTORY_RANGE.first..HANDLER_ADDON_MAIN_INVENTORY_RANGE.last - 9
@JvmField val HANDLER_ADDON_HOTBAR_RANGE = HANDLER_ADDON_MAIN_INVENTORY_WITHOUT_HOTBAR_RANGE.last + 1..HANDLER_ADDON_MAIN_INVENTORY_RANGE.last

@JvmField val INVENTORY_HOTBAR_RANGE = 0..8

@JvmField val INVENTORY_ADDON_DEEP_POCKETS_RANGE = 0 expandBy DEEP_POCKETS_MAX_SIZE
@JvmField val INVENTORY_ADDON_TOOL_BELT_RANGE = INVENTORY_ADDON_DEEP_POCKETS_RANGE.last + 1 expandBy TOOL_BELT_SIZE
@JvmField val INVENTORY_ADDON_UTILITY_BELT_RANGE = INVENTORY_ADDON_TOOL_BELT_RANGE.last + 1 expandBy UTILITY_BELT_SIZE