@file:JvmName("GeneralConstants")

package me.lizardofoz.inventorio.util

const val DEEP_POCKETS_MAX_LEVEL = 3
const val VANILLA_ROW_LENGTH = 9

const val MAIN_INVENTORY_SIZE = VANILLA_ROW_LENGTH * 4
const val DEEP_POCKETS_MAX_SIZE = DEEP_POCKETS_MAX_LEVEL * VANILLA_ROW_LENGTH
const val CRAFTING_GRID_SIZE = 5
const val ARMOR_SIZE = 4
const val UTILITY_BELT_SMALL_SIZE = 4
const val UTILITY_BELT_FULL_SIZE = 8

@JvmField val INVENTORY_HOTBAR_RANGE = 0..8
@JvmField val INVENTORY_ADDON_DEEP_POCKETS_RANGE = 0 expandBy DEEP_POCKETS_MAX_SIZE
@JvmField val INVENTORY_ADDON_UTILITY_BELT_RANGE = INVENTORY_ADDON_DEEP_POCKETS_RANGE.last + 1 expandBy UTILITY_BELT_FULL_SIZE
@JvmField val INVENTORY_ADDON_TOOL_BELT_INDEX_OFFSET = INVENTORY_ADDON_UTILITY_BELT_RANGE.last + 1