package me.lizardofoz.inventorio.util

const val DEEP_POCKETS_MAX_LEVEL = 3
const val VANILLA_ROW_LENGTH = 9

const val MAIN_INVENTORY_SIZE = VANILLA_ROW_LENGTH * 4
const val DEEP_POCKETS_MAX_SIZE = DEEP_POCKETS_MAX_LEVEL * VANILLA_ROW_LENGTH
const val ARMOR_SIZE = 4
const val TOOL_BELT_SIZE = 5
const val UTILITY_BELT_SIZE = 8

val HANDLER_CRAFTING_GRID_RANGE = 0 until 5
val HANDLER_ARMOR_RANGE = HANDLER_CRAFTING_GRID_RANGE.last + 1 expandBy ARMOR_SIZE
val HANDLER_MAIN_INVENTORY_RANGE = HANDLER_ARMOR_RANGE.last + 1 expandBy MAIN_INVENTORY_SIZE
val HANDLER_DUD_OFFHAND_RANGE = HANDLER_MAIN_INVENTORY_RANGE.last + 1 expandBy 1
val HANDLER_DEEP_POCKETS_RANGE = HANDLER_DUD_OFFHAND_RANGE.last + 1 expandBy DEEP_POCKETS_MAX_SIZE
val HANDLER_TOOL_BELT_RANGE = HANDLER_DEEP_POCKETS_RANGE.last + 1 expandBy TOOL_BELT_SIZE
val HANDLER_UTILITY_BELT_RANGE = HANDLER_TOOL_BELT_RANGE.last + 1 expandBy UTILITY_BELT_SIZE
val HANDLER_UTILITY_BELT_EXTENSION_RANGE = HANDLER_UTILITY_BELT_RANGE.first + 4 .. HANDLER_UTILITY_BELT_RANGE.last

val HANDLER_MAIN_WITHOUT_HOTBAR_RANGE = HANDLER_MAIN_INVENTORY_RANGE.first .. HANDLER_MAIN_INVENTORY_RANGE.last - 9
val HANDLER_HOTBAR_RANGE = HANDLER_MAIN_WITHOUT_HOTBAR_RANGE.last + 1 .. HANDLER_MAIN_INVENTORY_RANGE.last

val INVENTORY_ADDON_DEEP_POCKETS_RANGE = 0 expandBy DEEP_POCKETS_MAX_SIZE
val INVENTORY_ADDON_TOOL_BELT_RANGE = INVENTORY_ADDON_DEEP_POCKETS_RANGE.last + 1 expandBy TOOL_BELT_SIZE
val INVENTORY_ADDON_UTILITY_BELT_RANGE = INVENTORY_ADDON_TOOL_BELT_RANGE.last + 1 expandBy UTILITY_BELT_SIZE