# General Properties
    loom.platform=neoforge
    minecraft_version=1.21.1
    yarn_mappings=1.21.1+build.3
    # https://maven.architectury.dev/dev/architectury/yarn-mappings-patch-neoforge/
    yarn_mappings_patch=1.21+build.6
    game_versions=1.21\n1.21.1

# NeoForge and dependency version ranges
    minecraft_version_range_fabric=
    minecraft_version_range_forge=[1.21,)
    neoforge_version=21.1.215
    neoforge_version_range=[21.1,)

# Common Dependencies
    cloth_version=15.0.140
    # https://modrinth.com/mod/clumps/versions
    clumps_version=19.0.0.1-neoforge,1.21.1

# Fabric Dependencies
    # https://modrinth.com/mod/early-loading-screen/versions
    early_loading_screen_version=
    fabric_api_version=
    modmenu_version=
    # https://modrinth.com/mod/trinkets/versions?l=fabric
    trinkets_version=

# NeoForge Dependencies
    # https://maven.theillusivec4.top/top/theillusivec4/curios/curios-neoforge/
    curios_version=9.5.1+1.21.1
