package me.danetnaverno.inventorio.util

import java.awt.Point


val CANVAS_PLAYER_INVENTORY_TOP_WITH_DECO = Point(0, 0)
val CANVAS_PLAYER_INVENTORY_TOP_NO_DECO = Point(13, 13)

val CANVAS_PLAYER_INVENTORY_EXTENSION_WITH_DECO_P1 = Point(0, 197)
val CANVAS_PLAYER_INVENTORY_EXTENSION_WITH_DECO_P2 = Point(0, 264)

val CANVAS_PLAYER_INVENTORY_MAIN_WITH_DECO = Point(0, 96)
val CANVAS_PLAYER_INVENTORY_MAIN_NO_DECO = Point(13, 96)

val CANVAS_PLAYER_INVENTORY_UTILITY_EXT_WITH_DECO = Point(0, 286)
val CANVAS_PLAYER_INVENTORY_UTILITY_EXT_NO_DECO = Point(8, 294)

fun CANVAS_PLAYER_INVENTORY_TOOL_BELT_SLOT(slot: Int) = Point(39 + 16 * slot, 286)

val CANVAS_PLAYER_INVENTORY_UTILITY_SELECTION_WITH_DECO = Point(39, 307)
val CANVAS_PLAYER_INVENTORY_UTILITY_SELECTION_NO_DECO = Point(43, 311)

val CANVAS_PLAYER_INVENTORY_PHYS_BAR = Point(39, 344)


val CANVAS_EXTERNAL_INVENTORY_TOP_PART = Point(0, 0)
val CANVAS_EXTERNAL_INVENTORY_EXTENSION_PART_TOP = Point(0, 131)
val CANVAS_EXTERNAL_INVENTORY_EXTENSION_PART_BOTTOM = Point(0, 198)
val CANVAS_EXTERNAL_INVENTORY_MAIN_PART = Point(0, 30)
val CANVAS_EXTERNAL_INVENTORY_PHYS_BAR = Point(20, 215)

val CANVAS_CREATIVE_INVENTORY = Point(0, 0)
val CANVAS_CREATIVE_INVENTORY_PHYS_BAR = Point(12, 191)
val CANVAS_CREATIVE_INVENTORY_SEARCH_BAR = Point(101, 227)


const val CANVAS_QUICK_BAR_START_X = 0
const val CANVAS_QUICK_BAR_START_Y = 0
const val CANVAS_QUICK_BAR_WIDTH = 242
const val CANVAS_QUICK_BAR_SPLIT_START_X = 0
const val CANVAS_QUICK_BAR_SPLIT_START_Y = 46
const val CANVAS_QUICK_BAR_SPLIT_WIDTH = 254
const val CANVAS_QUICK_BAR_SECSEL_X = 152
const val CANVAS_QUICK_BAR_SECSEL_Y = 22
const val CANVAS_QUICK_BAR_SECSEL_W = 84
const val CANVAS_QUICK_BAR_SECSEL_H = 24